import { Inter } from 'next/font/google'
import './globals.css'


//components 
import Footer from './components/footer/footer'
import Header from './components/headerBar/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Project X',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
